po: return po/iso3166.tab.h back into POTFILES.in
po/iso3166.tab.h is a generated file containing country names to be translated.
The file is generated from /usr/share/zoneinfo/iso3166.tab by Rules-iso3166,
that gets appended to Makefile.
Rules-iso3166 is now updated to search for the input file in
$(datadir)/zoneinfo/iso3166.tab, and if not found in /usr/share/zoneinfo/iso3166.tab
When no input file is found, empty po/iso3166.tab.h is created and a warning
printed.

diff --git a/po/Rules-iso3166 b/po/Rules-iso3166
--- a/po/Rules-iso3166
+++ b/po/Rules-iso3166
@@ -1,8 +1,17 @@
 # For translation of country names (taken from /usr/share/zoneinfo/iso3166.tab)
-$(top_builddir)/po/iso3166.tab.h: $(datadir)/zoneinfo/iso3166.tab
-	@rm -f $(top_builddir)/po/iso3166.tab.h
-	@cat $(datadir)/zoneinfo/iso3166.tab | grep -v "#" | cut -f 2 | while read country ; do \
-		echo "char *s = N_(\"$${country}\")" >> $(top_builddir)/po/iso3166.tab.h ; \
+$(top_builddir)/po/iso3166.tab.h:
+	@rm -f $(top_builddir)/po/iso3166.tab.h; \
+	countries="$(datadir)/zoneinfo/iso3166.tab"; \
+	if test ! -f $$countries; then \
+		countries="/usr/share/zoneinfo/iso3166.tab"; \
+		if test ! -f $$countries; then \
+			echo "Warning: file $$countries not found; country names won't be translated. Please install tzdata to fix it." 1>&2; \
+			touch $(top_builddir)/po/iso3166.tab.h ; \
+			exit 0; \
+		fi \
+	fi; \
+	cat $$countries | grep -v "#" | cut -f 2 | while read country ; do \
+		echo "char *s = N_(\"$${country}\")" >> $(top_builddir)/po/iso3166.tab.h; \
 	done
 
 mostlyclean-iso3166:
